github:
  username: ${{ github.actor }}
  token:    ${{ secrets.GITHUB_TOKEN }}

package:
  repositories:   ["ghcr.io/amp-buildpacks/leo-dist"]
  register:       true
  registry_token: ${{ secrets.GITHUB_TOKEN }}

docker_credentials:
  - registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

dependencies:
- id: leo-gnu
  uses: docker://ghcr.io/amp-buildpacks/actions/leo-dependency:main
  with:
    target: x86_64-unknown-linux-gnu
    token: ${{ secrets.GITHUB_TOKEN }}
- id: leo-musl
  uses: docker://ghcr.io/amp-buildpacks/actions/leo-dependency:main
  with:
    target: x86_64-unknown-linux-musl
    token: ${{ secrets.GITHUB_TOKEN }}
